name: Node.js Continuous Integration
on:
  push:
    branches: ['master']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js @{{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Run test cases
        run: yarn run test
      - name: Build the project
        run: yarn run build
      - name: Release
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:joakimhedberg/valheim-status.git
          BRANCH: release
          FOLDER: dist
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}